server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"

metadata:
  connector:
    connector-id: http-forwarder
    api-base-url: http://localhost:3000
    org-id: demo-org
    heartbeat-interval-ms: 15000
